use std::env;
use std::path::PathBuf;

fn main() {
    pkg_config::probe_library("crypto")
        .expect("cannot find OpenSSL library (libcrypto)");

    println!("cargo: rustc-link-lib=crypto");

    let bindings = bindgen::Builder::default()
        .header("/usr/include/openssl/md5.h")
        .allowList_function("MD5_.*")
        .parse_callbacks(Box::new(bindgen::CargoCallbacks::new()))
        .generate()
        .expect("cannot generate bindings for OpenSSL MD5 API");

    // We should set 'OUT_DIR' directory to save new rust code
    // generated by bindgen
    let out_path = PathBuf::from(env::var("OUT_DIR").unwrap());
    bindings
        .write_to_file(out_path.join("bindings.rs"))
        .expect("cannot write file bindings.rs");
}
