[package]
name = "doge-rust"
version = "0.1.0"
authors = ["Dr.Mard <sergej.khrumalo@gmail.com>"]
description = "Straightforward DOGE-like blockchain"
license = ""
edition = "2021"

[dependencies]
sha2 = "0.10"
chrono = "0.4"
ed25519-dalek = { version = "2.1", features = ["serde"] }
rand = "0.8"
tokio = { version = "1.35", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

